# Generated by Django 4.2.1 on 2023-07-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CO2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('sensor_nb', models.IntegerField()),
                ('created_time', models.DateTimeField()),
                ('uptime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('sensor_nb', models.IntegerField()),
                ('created_time', models.DateTimeField()),
                ('uptime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('sensor_nb', models.IntegerField()),
                ('created_time', models.DateTimeField()),
                ('uptime', models.DateTimeField()),
            ],
        ),
    ]
