# Generated by Django 4.2.1 on 2023-07-24 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recolte_nb', models.CharField(default=None, max_length=5)),
                ('column', models.CharField(max_length=2)),
                ('date', models.DateTimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='MiseEnCulture',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_tracability.action')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api_tracability.action',),
        ),
        migrations.CreateModel(
            name='NourrisageHumide',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_tracability.action')),
                ('given_quantity', models.IntegerField()),
                ('marc_arrival_date', models.DateTimeField()),
                ('anomaly', models.BooleanField()),
                ('anomaly_comment', models.TextField(default=None)),
                ('is_imw100_weighted', models.BooleanField()),
                ('imw100_weight', models.IntegerField(default=None)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api_tracability.action',),
        ),
        migrations.CreateModel(
            name='NourrisageSon',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_tracability.action')),
                ('given_quantity', models.IntegerField()),
                ('son_arrival_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api_tracability.action',),
        ),
        migrations.CreateModel(
            name='Recolte',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_tracability.action')),
                ('harvested_quantity', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api_tracability.action',),
        ),
        migrations.CreateModel(
            name='Tamisage',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_tracability.action')),
                ('sieved_quantity', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('api_tracability.action',),
        ),
    ]
