# Generated by Django 4.2.1 on 2023-07-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('NHUM', 'Nourrisage Humide'), ('NSON', 'Nourrisage Son'), ('TAMI', 'Tamisage'), ('RECO', 'Recolte')], max_length=4)),
                ('column', models.CharField(max_length=2)),
                ('recolte_nb', models.IntegerField()),
                ('created_time', models.DateTimeField()),
                ('uptime', models.DateTimeField()),
            ],
        ),
    ]
