# Generated by Django 4.2.1 on 2023-07-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tracability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nourrisagehumide',
            name='anomaly_comment',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='nourrisagehumide',
            name='imw100_weight',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
