# Generated by Django 4.2.1 on 2023-07-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tracability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('CULT', 'Mise En Culture'), ('NHUM', 'Nourrisage Humide'), ('NSON', 'Nourrisage Son'), ('TAMI', 'Tamisage'), ('RECO', 'Recolte')], max_length=4),
        ),
        migrations.AlterField(
            model_name='action',
            name='recolte_nb',
            field=models.CharField(max_length=5),
        ),
    ]
