# Generated by Django 4.2.1 on 2023-08-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tracability', '0002_alter_nourrisagehumide_anomaly_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nourrisagehumide',
            name='given_quantity_bac',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nourrisageson',
            name='given_quantity_bac',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nourrisagehumide',
            name='anomaly_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nourrisagehumide',
            name='imw100_weight',
            field=models.IntegerField(blank=True),
        ),
    ]
