# Generated by Django 4.2.1 on 2023-07-20 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_tracability', '0002_alter_action_action_type_alter_action_recolte_nb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type_name', models.CharField(choices=[('CULT', 'Mise En Culture'), ('NHUM', 'Nourrisage Humide'), ('NSON', 'Nourrisage Son'), ('TAMI', 'Tamisage'), ('RECO', 'Recolte')], max_length=4)),
                ('column', models.CharField(max_length=2)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MiseCultureAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='action',
            name='action_type',
        ),
        migrations.CreateModel(
            name='MarcAction',
            fields=[
                ('actiondetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_tracability.actiondetail')),
                ('given_quantity', models.IntegerField()),
                ('marc_arrival_date', models.DateTimeField()),
                ('anomaly', models.BooleanField()),
                ('anomaly_comment', models.TextField()),
                ('is_imw100_weighted', models.BooleanField()),
                ('imw100_weight', models.IntegerField()),
            ],
            bases=('api_tracability.actiondetail',),
        ),
        migrations.CreateModel(
            name='RecolteAction',
            fields=[
                ('actiondetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_tracability.actiondetail')),
                ('harvested_quantity', models.IntegerField()),
            ],
            bases=('api_tracability.actiondetail',),
        ),
        migrations.CreateModel(
            name='SonAction',
            fields=[
                ('actiondetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_tracability.actiondetail')),
                ('given_quantity', models.IntegerField()),
                ('son_arrival_date', models.DateTimeField()),
            ],
            bases=('api_tracability.actiondetail',),
        ),
        migrations.CreateModel(
            name='TamisageAction',
            fields=[
                ('actiondetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_tracability.actiondetail')),
                ('sieved_quantity', models.IntegerField()),
            ],
            bases=('api_tracability.actiondetail',),
        ),
        migrations.AddField(
            model_name='action',
            name='action_detail',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_tracability.actiondetail'),
        ),
    ]
