# Generated by Django 4.2.1 on 2023-09-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tracability', '0003_nourrisagehumide_given_quantity_bac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nourrisagehumide',
            name='anomaly_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nourrisagehumide',
            name='imw100_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
