# Generated by Django 4.2.1 on 2023-09-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tracability', '0004_alter_nourrisagehumide_anomaly_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='recolte_nb',
            field=models.CharField(default=None, max_length=6),
        ),
    ]
