# Generated by Django 4.2.1 on 2023-10-14 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api_tracability", "0006_rename_nourrisagehumide_nourrissagehumide_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
