# Generated by Django 4.2.1 on 2023-10-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_tracability", "0008_alter_action_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nourrissagehumide",
            name="given_quantity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="nourrissagehumide",
            name="given_quantity_bac",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="nourrissagehumide",
            name="imw100_weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nourrissageson",
            name="given_quantity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="nourrissageson",
            name="given_quantity_bac",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="recolte",
            name="harvested_quantity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="tamisage",
            name="sieved_quantity",
            field=models.FloatField(),
        ),
    ]
